const { VITE_BASE_URL, VITE_REDUX_PERSIST_SECRET_KEY, VITE_WORD_AUDIO_PLAYBACK_BASE_URL } =
  import.meta.env as {
    [key: string]: string;
  };

export const APP = {
  BASE_URL: `${VITE_BASE_URL}/`,
  REDUX_PERSIST_SECRET_KEY: VITE_REDUX_PERSIST_SECRET_KEY,
  WORD_AUDIO_PLAYBACK_BASE_URL: VITE_WORD_AUDIO_PLAYBACK_BASE_URL,
};
